import {api} from '../http.js';
import {escape,icon,link,notice,field,select,textarea,errorSlot,bindForm,flash,toast,money} from '/ui/components.js';
const steps=['Identification','Documents','Caractéristiques','Équipements','Photos','Sécurité','Prix et règles','Disponibilités','Récapitulatif'];
export async function wizard(me){if(!me.owner){location.replace('/owner/start');return;}let draft=await api('/owner/draft'),step=Math.min(9,Math.max(1,Number(new URLSearchParams(location.search).get('step'))||1));const start=new Date(Date.now()+86400000).toISOString().slice(0,16),end=new Date(Date.now()+180*86400000).toISOString().slice(0,16);const d={name:'',plate:'DEMO-001',year:2022,city:'Le Gosier',category:'Citadine',gearbox:'Manuelle',fuel:'Essence',seats:5,price:32,description:'',equipment:[],photos:0,start,end,...draft};
 let body='';if(step===1)body=field('Nom / modèle','name',d.name,'text','required minlength="2" maxlength="80"')+field('Plaque fictive uniquement','plate',d.plate,'text','required minlength="3" maxlength="20"')+field('Année','year',d.year,'number','required min="1950" max="2030"')+select('Commune','city',['Le Gosier','Sainte-Anne','Baie-Mahault','Pointe-à-Pitre','Basse-Terre'],d.city);
 if(step===2)body=notice('Ne téléversez aucune vraie pièce. Le bouton ci-dessous ajoute trois justificatifs synthétiques : carte grise, assurance et contrôle technique. Leur contrôle sera individuel.')+`<label class="check"><input type="checkbox" name="documents" ${d.documents?'checked':''} required>Ajouter les trois documents fictifs</label><p>Ils seront soumis au back-office avec l’annonce. Un contrôle humain ne garantit pas automatiquement leur authenticité.</p>`;
 if(step===3)body=select('Catégorie','category',['Citadine','SUV','Utilitaire'],d.category)+select('Boîte','gearbox',['Manuelle','Automatique'],d.gearbox)+select('Énergie','fuel',['Essence','Diesel','Hybride','Électrique'],d.fuel)+field('Places','seats',d.seats,'number','required min="2" max="9"');
 if(step===4)body=`<p>Choisissez les équipements présents.</p>${['Climatisation','Bluetooth','Siège enfant','Caméra recul'].map(e=>`<label class="check"><input type="checkbox" name="equipment" value="${e}" ${d.equipment.includes(e)?'checked':''}>${e}</label>`).join('')}`;
 if(step===5)body=`<p>Cinq vues illustratives pour présenter votre véhicule. Aucun fichier personnel n’est demandé.</p><div class="photo-grid">${['Avant','Arrière','Profil gauche','Profil droit','Habitacle'].map((v,n)=>`<div class="photo-slot"><img src="/assets/car-sage.svg" alt="Illustration fictive ${v}"><strong>${v}</strong><label class="check"><input name="photo${n}" type="checkbox" ${d.photos>n?'checked':''} required>Ajouter cette vue fictive</label></div>`).join('')}</div>`;
 if(step===6)body=notice('Aucun suivi GPS, aucune assurance automatique. Le contrôle de l’aptitude à la location rémunérée reste nécessaire.')+`<label class="check"><input name="safety" type="checkbox" ${d.safety?'checked':''} required>J’ai compris que les conditions de sécurité et de couverture doivent être contrôlées.</label><button type="button" disabled>Traceur non disponible dans cette démo</button>`;
 if(step===7)body=field('Prix journalier fictif (€)','price',d.price,'number','required min="1" max="1000"')+textarea('Présentation et règles du véhicule','description',d.description,'required minlength="10" maxlength="1500"')+`<label class="check"><input name="pets" type="checkbox" ${d.pets?'checked':''}>Animaux acceptés</label><p>Véhicule non-fumeur. Forfait kilométrique, dépassement, commission et caution : non définis. Aucun montant libre de caution n’est collecté.</p>`;
 if(step===8)body=field('Disponible du (heure Guadeloupe)','start',d.start,'datetime-local','required')+field('Au','end',d.end,'datetime-local','required')+notice('Territoire de démonstration : Guadeloupe continentale. Les sorties inter-îles restent indisponibles.')+'<button type="button" disabled>Marie-Galante / Les Saintes / La Désirade</button>';
 if(step===9)body=`<img class="cover" src="/assets/car-sage.svg" alt="Illustration fictive"><h2>${escape(d.name||'Nom à compléter')}</h2><p>${escape(d.city)} · ${escape(d.category)} · ${escape(d.gearbox)} · ${d.seats} places</p><p>${money(d.price)} / jour fictif · ${d.photos} vues · ${d.documents?'3 justificatifs synthétiques':'Documents manquants'}</p><p>${escape(d.description)}</p>${notice('L’envoi ne publie pas l’annonce. Un agent doit vérifier chaque justificatif et motiver sa décision sur l’annonce.')}<label class="check"><input type="checkbox" name="finalConfirm" required>Soumettre cette annonce fictive à la revue.</label>`;
 document.getElementById('main').innerHTML=`<a href="/owner/vehicles">${icon('back')} Mon parc</a><div class="section-heading section"><div><p class="eyebrow">Nouvelle annonce · brouillon sauvegardé dans l’API</p><h1>Votre véhicule, pas à pas.</h1></div><span>Étape ${step} / 9</span></div><div class="wizard"><nav class="wizard-steps" aria-label="Étapes">${steps.map((s,n)=>`<a href="?step=${n+1}" ${n+1===step?'aria-current="step"':''}><span>${n+1}</span>${s}</a>`).join('')}</nav><article class="card"><h2>${steps[step-1]}</h2><form id="wizard-form">${body}${errorSlot}<div class="form-actions">${step>1?link('?step='+(step-1),'Précédent','secondary'):''}<button type="button" id="save-draft" class="secondary">Sauvegarder et quitter</button><button type="submit">${step===9?'Envoyer pour validation':'Enregistrer et continuer'}</button></div></form></article></div>`;
 const collect=()=>{const f=document.getElementById('wizard-form'),b=Object.fromEntries(new FormData(f));if(step===2)b.documents=!!b.documents;if(step===4)b.equipment=new FormData(f).getAll('equipment');if(step===5)b.photos=[0,1,2,3,4].filter(n=>b['photo'+n]).length;if(step===6)b.safety=!!b.safety;if(step===7)b.pets=!!b.pets;return {...d,...b,year:Number(b.year??d.year),seats:Number(b.seats??d.seats),price:Number(b.price??d.price),step};};document.getElementById('save-draft').onclick=async()=>{try{await api('/owner/draft',collect());flash('Brouillon enregistré. Reprenez avec « Ajouter un véhicule ».');location.href='/owner/vehicles';}catch(e){toast(e.message);}};
 bindForm('wizard-form',async()=>{const b=collect();if(step===8&&new Date(b.end)<=new Date(b.start))throw new Error('Le retour doit suivre le début de disponibilité.');await api('/owner/draft',b);if(step<9){location.href='?step='+(step+1);return;}if(!b.safety)throw new Error('Complétez l’étape Sécurité avant l’envoi.');const v=await api('/owner/vehicles',{...b,start:b.start+'-04:00',end:b.end+'-04:00'});flash('Annonce envoyée. Les trois justificatifs et l’annonce attendent une revue.');location.href='/owner/vehicles/'+v.id;});}
