export const escape = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={search:'m21 21-5-5 M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14',car:'M3 16h18v-6l-3-5H6l-3 5v6 M3 10h18 M6 16v3 M18 16v3 M6 13h2 M16 13h2',home:'m3 10 9-7 9 7 M5 9v12h5v-7h4v7h5V9',calendar:'M5 5h14v16H5z M8 3v4 M16 3v4 M5 10h14',message:'M3 4h18v13H8l-5 4V4',user:'M8 7a4 4 0 1 0 8 0 4 4 0 0 0-8 0 M4 22v-3a8 8 0 0 1 16 0v3',bell:'M5 17h14l-2-4V9a5 5 0 0 0-10 0v4z M10 21h4',arrow:'M5 12h14 M13 6l6 6-6 6',back:'M19 12H5 M11 6l-6 6 6 6',check:'m4 12 5 5L20 6',close:'m6 6 12 12 M18 6 6 18',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z m-4 9 3 3 5-6',camera:'M3 7h4l2-3h6l2 3h4v14H3z M8 13a4 4 0 1 0 8 0 4 4 0 0 0-8 0',pin:'M12 22s7-8 7-13a7 7 0 0 0-14 0c0 5 7 13 7 13 M9 9a3 3 0 1 0 6 0 3 3 0 0 0-6 0',menu:'M4 6h16 M4 12h16 M4 18h16',plus:'M12 4v16 M4 12h16',alert:'m12 3 10 18H2z M12 9v5 M12 17v1',wallet:'M3 5h18v15H3z M16 10h5v5h-5z',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',file:'M5 3h9l5 5v13H5z M14 3v6h5 M8 13h8 M8 17h6',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',logout:'M10 4H4v16h6 M10 12h12 M17 7l5 5-5 5',refresh:'M20 8a8 8 0 1 0 0 9 M20 3v6h-6',lock:'M5 10h14v11H5z M8 10V7a4 4 0 1 1 8 0v3',clock:'M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16 M12 7v5l4 2'};
export const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;
export const money=v=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v||0);
export const date=v=>v?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Guadeloupe'}).format(new Date(v)):'—';
export const statuses={requested:'En attente du propriétaire',awaiting_payment:'Acceptée · paiement attendu',confirmed:'Réservation confirmée',in_progress:'Location en cours',return_reported:'Retour déclaré',returned:'Récupération vérifiée',completed:'Clôturée',declined:'Demande refusée',withdrawn:'Retirée',pending:'En attente de contrôle',verified:'Vérifié · simulation',rejected:'Refusé',missing:'À compléter',published:'En ligne · démo',paused:'En pause',changes_requested:'Modifications demandées',active:'Actif',suspended:'Suspendu',not_started:'Non initié',failed:'Échec simulé',simulated_paid:'Paiement simulé réussi',simulated_authorized:'Autorisation simulée',simulated_failed:'Échec simulé',pending_approval:'Validation secondaire requise',approved:'Approuvé · simulation',simulated_executed:'Exécuté fictivement',received:'Reçu',evidence_requested:'Pièces demandées',contradictory:'Échanges contradictoires',reviewing:'En examen',decision:'Décision motivée',closed:'Clos'};
export function badge(s){return `<span class="badge ${['rejected','declined','suspended','failed','simulated_failed'].includes(s)?'danger':['verified','published','completed','confirmed','approved'].includes(s)?'success':['pending','requested','awaiting_payment','pending_approval','changes_requested'].includes(s)?'warning':'neutral'}">${escape(statuses[s]||s)}</span>`;}
export const link=(href,label,style='')=>`<a class="button ${style}" href="${escape(href)}">${label}</a>`;
export const notice=(msg,type='')=>`<div class="notice ${type}">${icon(type==='error'?'alert':'shield')}<div>${msg}</div></div>`;
export const empty=(title,description,action='')=>`<div class="empty card">${icon('search')}<h2>${escape(title)}</h2><p class="muted">${escape(description)}</p>${action}</div>`;
export const field=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${escape(value)}" ${extra}></label>`;
let controlSequence=0;
export const select=(label,name,options,value='')=>{const id='select-'+(++controlSequence);return `<div class="field"><label for="${id}">${label}</label><select id="${id}" name="${name}">${options.map(o=>{let [v,l]=Array.isArray(o)?o:[o,o];return `<option value="${escape(v)}" ${String(v)===String(value)?'selected':''}>${escape(l)}</option>`;}).join('')}</select></div>`;};
export const textarea=(label,name,value='',extra='')=>`<label class="field"><span>${label}</span><textarea name="${name}" ${extra}>${escape(value)}</textarea></label>`;
export const errorSlot='<div class="form-error" role="alert"></div>';
export const formValues=form=>Object.fromEntries(new FormData(form));
export function toast(message){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.role='status';t.textContent=message;document.body.append(t);setTimeout(()=>t.remove(),5000);}
export function flash(message){sessionStorage.setItem('flash',message);}
export function showFlash(){const m=sessionStorage.getItem('flash');if(m){sessionStorage.removeItem('flash');toast(m);}}
export function modal(title,content,onSubmit){const trigger=document.activeElement;const d=document.createElement('dialog');d.innerHTML=`<form><div class="row between"><h2>${escape(title)}</h2><button type="button" class="link-button" data-close aria-label="Fermer">${icon('close')}</button></div>${content}${errorSlot}<div class="form-actions"><button type="button" class="secondary" data-close>Annuler</button>${onSubmit?'<button type="submit">Confirmer</button>':''}</div></form>`;document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>{d.remove();trigger?.focus();});if(onSubmit)d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{await onSubmit(formValues(f),f);d.close();}catch(err){f.querySelector('.form-error').textContent=err.message;}finally{btn.disabled=false;}};d.showModal();return d;}
export function bindForm(id,fn){const f=document.getElementById(id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();if(!f.reportValidity())return;const buttons=f.querySelectorAll('button[type=submit]');buttons.forEach(b=>b.disabled=true);f.querySelector('.form-error')?.replaceChildren();try{await fn(formValues(f),f);}catch(err){const slot=f.querySelector('.form-error');if(slot){slot.textContent=err.message;slot.tabIndex=-1;slot.focus();}else toast(err.message);}finally{buttons.forEach(b=>b.disabled=false);}});}
export function bindActions(selector,fn){document.querySelectorAll(selector).forEach(el=>el.addEventListener('click',async()=>{el.disabled=true;try{await fn(el);}catch(e){modal('Action non réalisée',`<p>${escape(e.message)}</p>`);}finally{el.disabled=false;}}));}
export const kv=(label,value)=>`<div class="key-value"><dt>${escape(label)}</dt><dd>${value}</dd></div>`;
export const shellLoading=`<div class="loading" role="status" aria-label="Chargement"><div class="skeleton line"></div><div class="grid"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div><span class="sr-only">Chargement en cours</span></div>`;
